"""Initial schema

Revision ID: 8ee3e2cd843e
Revises: 
Create Date: 2025-08-21 20:31:07.875319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee3e2cd843e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('schedule', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='restaurant'
    )
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('restaurant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='restaurant'
    )
    op.create_table('menu_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['restaurant.categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='restaurant'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_items', schema='restaurant')
    op.drop_table('categories', schema='restaurant')
    op.drop_table('restaurants', schema='restaurant')
    # ### end Alembic commands ###
